Update springboot 2.7.8
sofastack/sofa-boot pull request #1071
Opened 2023-02-08 09:45 UTC by crazysaltfish

Update springboot 2.7.8

2023-02-08 09:59 UTC, HzjNeverStop requested changes
LGTM

2023-02-08 09:59 UTC, HzjNeverStop commented on sofa-boot-project/sofa-boot-starters/tracer-sofa-boot-starter/pom.xml
> +            <artifactId>mysql-connector-j</artifactId>
springboot 小版本升级需要升级mysql connector版本？这个改动有点大，是必须的吗

2023-02-09 02:58 UTC, crazysaltfish reviewed
delete <mysql.version>

2023-02-09 02:59 UTC, HzjNeverStop approved these changes
LGTM

2023-02-09 10:21 UTC, merged