reactor switch on scenes
sofastack/sofa-boot pull request #1106
Opened 2023-03-06 04:02 UTC by taobaorun

reactor switch on scenes
1. add sofa.boot.scenes.enable env key to open scene
2. scenes config files on sofa-boot/scenes

2023-03-06 09:53 UTC, HzjNeverStop requested changes

2023-03-06 09:53 UTC, HzjNeverStop commented on sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/env/ScenesEnvironmentPostProcessor.java
> +    private static final String SCENE_ENABLE    = "sofa.boot.scenes.enable";
key 为 sofa.boot.scenes=xxx，加上.enable 的话，value更像是填true/false

2023-03-06 09:53 UTC, HzjNeverStop commented on sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/env/ScenesEnvironmentPostProcessor.java
> +            propertySourceLoaders, List.of(scenes.split(",")));
可以用 StringUtils.commaDelimitedListToSet() 代替原生的 split

2023-03-06 09:53 UTC, HzjNeverStop commented on sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/env/ScenesEnvironmentPostProcessor.java
> +        if (sceneConfigDataReferences != null && !sceneConfigDataReferences.isEmpty()) {
91 行的判断不需要

2023-03-09 01:08 UTC, taobaorun commented on sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/env/ScenesEnvironmentPostProcessor.java
> +    private static final String SCENE_ENABLE    = "sofa.boot.scenes.enable";
done

2023-03-09 01:11 UTC, taobaorun commented on sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/env/ScenesEnvironmentPostProcessor.java
> +            propertySourceLoaders, List.of(scenes.split(",")));
done

2023-03-09 05:58 UTC, HzjNeverStop approved these changes
LGTM

2023-03-09 05:59 UTC, merged