Feature same module inject
sofastack/sofa-boot pull request #1116
Opened 2023-03-15 06:10 UTC by taobaorun

1.componentinfo add more details for components endpoint.
2.reference check support skip by interface & uniqueId

2023-03-15 08:17 UTC, HzjNeverStop requested changes

2023-03-15 08:25 UTC, taobaorun commented on sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/component/ComponentDefinitionInfo.java
> +    private SourceType         sourceType;
ok

2023-03-15 08:31 UTC, taobaorun commented on sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/SofaRuntimeProperties.java
> +    private static final ConcurrentHashMap<ClassLoader, String[]> skipJvmReferenceHealthCheckArrayMap = new ConcurrentHashMap<>();
ok

2023-03-15 08:31 UTC, taobaorun commented on sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/configure/SofaRuntimeConfigurationProperties.java
> +    public void setSkipJvmReferenceHealthCheckArray(String[] skipJvmReferenceHealthCheckArray) {
ok

2023-03-15 08:32 UTC, taobaorun commented on sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ReferenceComponent.java
> +    private Map<String, Property>     properties               = new ConcurrentHashMap<>();
ok

2023-03-15 08:32 UTC, taobaorun commented on sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/component/ReferenceComponent.java
> +                .getSkipJvmReferenceHealthCheckArray(Thread.currentThread().getContextClassLoader());
ok

2023-03-15 08:45 UTC, taobaorun commented on sofa-boot-project/sofa-boot-autoconfigure/src/test/java/com/alipay/sofa/autoconfigure/test/runtime/SofaRuntimePropertiesTest.java
> +                                  "com.alipay.sofa.boot.skipJvmReferenceHealthCheckArray=com.alipay.sofa.isle.sample.facade.SampleJvmService:annotationImpl,com.alipay.sofa.isle.sample.facade.SampleJv
done

2023-03-15 08:59 UTC, HzjNeverStop commented on sofa-boot-project/sofa-boot-actuator/src/main/java/com/alipay/sofa/boot/actuator/components/SofaBootComponentsEndPoint.java
> +                        String applicationId = componentInfo.getApplicationContext() == null ? "null"
补充下相关的测试用例，验证getProperties的读取正确？

2023-03-16 02:13 UTC, HzjNeverStop approved these changes
LGTM

2023-03-16 03:23 UTC, merged