feat: support triple thread monitor
sofastack/sofa-boot pull request #711
Opened 2020-09-09 06:04 UTC by OrezzerO

feat: support triple thread monitor

2020-10-01 02:35 UTC, ujjboy requested changes

2020-10-01 02:35 UTC, ujjboy commented on sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ServerConfigContainer.java
> +                new RpcThreadPoolMonitor(threadPoolExecutor, LoggerConstant.BOLT_THREAD_LOGGER_NAME)
这个对象要记录下来，start 的时候 new 出来的话， stop 的时候要销毁

2020-10-01 02:35 UTC, ujjboy commented on sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ServerConfigContainer.java
> +            new RpcThreadPoolMonitor(threadPoolExecutor, LoggerConstant.TRIPLE_THREAD_LOGGER_NAME)
这个对象要记录下来，start 的时候 new 出来的话， stop 的时候要销毁

2020-10-09 03:12 UTC, OrezzerO commented on sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ServerConfigContainer.java
> +                new RpcThreadPoolMonitor(threadPoolExecutor, LoggerConstant.BOLT_THREAD_LOGGER_NAME)
已修复 @ujjboy

2020-10-09 13:05 UTC, ujjboy requested changes

2020-10-09 13:05 UTC, ujjboy commented on sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/common/RpcThreadPoolMonitor.java
> +                                    logger.error("Error happen the thread pool watch sleep ");
这句错误的英文改下吧，读起来不通顺啊。

2020-10-09 13:05 UTC, ujjboy commented on sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/common/RpcThreadPoolMonitor.java
>                                      sleep(30000);
这个值 30000 建议做成一个属性  或者一个配置项

2020-10-09 13:05 UTC, ujjboy commented on sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/common/RpcThreadPoolMonitor.java
> +        this.threadPoolExecutor = null;
startTimes 的作用是？  这里需要减1 吗？

2020-10-09 14:18 UTC, OrezzerO commented on sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/common/RpcThreadPoolMonitor.java
> +                                    logger.error("Error happen the thread pool watch sleep ");
已修改

2020-10-09 14:21 UTC, OrezzerO commented on sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/common/RpcThreadPoolMonitor.java
>                                      sleep(30000);
已修改

2020-10-09 14:21 UTC, OrezzerO commented on sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/common/RpcThreadPoolMonitor.java
> +        this.threadPoolExecutor = null;
恩需要的，已修改

2020-10-09 15:50 UTC, ujjboy requested changes

2020-10-09 15:50 UTC, ujjboy commented on sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/common/RpcThreadPoolMonitor.java
> +        this.threadPoolExecutor = null;
start()  stop() 能随意调的话，这个 threadPoolExecutor 可能不需要置为 null。

2020-10-09 15:50 UTC, ujjboy commented on sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/common/RpcThreadPoolMonitor.java
> +        this.active = false;
想了下  start()  stop() 如果被并发调的话， active 换成 AtomicBoolean 是不是更合理一些？

2020-10-10 02:35 UTC, OrezzerO commented on sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/common/RpcThreadPoolMonitor.java
> +        this.threadPoolExecutor = null;
我添加了 threadPoolExecutor 的set方法，每次调用前重新设置 threadPoolExecutor 吧

2020-10-10 02:36 UTC, OrezzerO commented on sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/common/RpcThreadPoolMonitor.java
> +        this.active = false;
改成AtomicBoolean 也不能保证并发情况下的线程安全，我在 start  和 stop 方法上加了两个 synchronized 锁来保证线程安全

2020-10-10 06:38 UTC, ujjboy approved these changes
LGTM

2020-10-10 07:05 UTC, glmapper approved these changes
LGTM

2020-10-10 07:06 UTC, merged