Support service/reference register hook and some refinements.
sofastack/sofa-boot pull request #803
Opened 2021-01-19 07:34 UTC by alaneuler

2021-01-19 07:41 UTC, glmapper requested changes

2021-01-19 07:41 UTC, glmapper commented on pom.xml
> +    <version>3.5.0-SNAPSHOT</version>
版本修改单独提一个 PR ，先把主站版本升级到 3.5.0-SNAPSHOT

2021-01-19 07:41 UTC, glmapper commented on sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/util/ConfigUtil.java
> +    public static void setRegistry(RpcBindingParam param,
补充下代码注释

2021-01-19 07:41 UTC, glmapper commented on sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/api/ReferenceRegisterHook.java
> +    void after(Object target);
建议透出 before 中的参数

2021-01-19 07:41 UTC, glmapper commented on sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/api/ServiceRegisterHook.java
> +    void after();
建议透出 before 中的参数

2021-01-20 05:22 UTC, alaneuler commented on pom.xml
> +    <version>3.5.0-SNAPSHOT</version>
这个正式提 pr 的时候，我操作一下

2021-01-20 07:22 UTC, HzjNeverStop approved these changes
LGTM

2022-07-25 07:55 UTC, closed without merging