Improve HealthCheck: add progress and timeout.(#837)
sofastack/sofa-boot pull request #844
Opened 2021-07-06 14:43 UTC by it-linnan

# 检查进度的实现

## 进度日志

### HealthChecker

1. 在检查前输出了`HealthChecker`的数量和名称，其中名称是通过调用`HealthChecker.getComponentName`方法获取的
1. 在指定HealthChecker检查前，输出了check start日志

### HealthIndicator

1. 在检查前输出了`HealthIndicator`的数量和名称，其中名称使用的是beanId
1. 在指定HealthIndicator检查前，输出了check start日志

## 超时机制

超时基于线程池实现:
1. 健康检查任务提交到线程池
1. 通过`Future.get(timeout)`等待检查结果
1. 超时(TimeoutException)则认为检查失败，且健康状态为未知(`Status.UNKNOWN`)

### HealthChecker

`HealthChecker`接口增加了`getTimeout`方法，用于获取超时时间。超时时间小于等于0时，使用默认的超时时间。

### HealthIndicator

`HealthIndicator`超时时间通过配置属性获取。未配置超时时间，或配置的超时时间小于等于0时，使用默认的超时时间。
配置属性的key遵循格式: `com.alipay.sofa.healthcheck.indicator.timeout.${beanId}`。

## 新增参数

```
# 健康检查默认超时时间 默认值为 10s
com.alipay.sofa.healthcheck.default.timeout=10000
# 组件健康检查超时时间 默认值为 10s
com.alipay.sofa.healthcheck.component.timeout=10000
# sofaboot模块健康检查超时时间 默认值为 10s
com.alipay.sofa.healthcheck.module.timeout=10000
# HealthIndicator健康检查超时时间 其中beanId需替换成实际值(mongoHealthIndicator,dbHealthIndicator,redisHealthIndicator...)
com.alipay.sofa.healthcheck.indicator.timeout.${beanId}=
# 健康检查线程池核心线程数 默认值为 CPU 核数 + 1
com.alipay.sofa.healthcheck.thread.pool.core.size=CPU+1
# 健康检查线程池最大线程数 默认值为 CPU 核数 + 1
com.alipay.sofa.healthcheck.thread.pool.max.size=CPU+1
```

2021-08-13 07:17 UTC, alaneuler requested changes

2021-08-13 07:17 UTC, alaneuler commented on sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/HealthCheckerProcessor.java
> +                .map(HealthChecker::getComponentName).collect(Collectors.joining(","));
此处需要 filter，任意一个 healthChecker 不一定是 readiness healthChecker

2021-08-13 07:17 UTC, alaneuler commented on sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/HealthCheckerProcessor.java
> +                    .submitTask(environment, healthChecker::isHealthy);
实际上，此处只需要一个单线程的线程池就够了，core、max size 配置感觉是多余的？

2021-08-13 07:17 UTC, alaneuler commented on sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/constant/SofaBootConstants.java
> +     * thread pool core size to execute health check.
不是 core size，是 max size

2021-08-13 07:17 UTC, alaneuler commented on sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/constant/SofaBootConstants.java
> +    public static final int     SOFABOOT_HEALTH_CHECK_DEFAULT_TIMEOUT_VALUE                  = 10 * 1000;
这个 10s 可能不够，建议改成 60s

2021-08-13 07:18 UTC, alaneuler commented
@it-linnan 思路很清晰，有些小细节可能需要改下～

2021-08-17 16:55 UTC, it-linnan commented on sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/HealthCheckerProcessor.java
> +                .map(HealthChecker::getComponentName).collect(Collectors.joining(","));
增加了filter，判断healthChecker是否实现了NonReadinessCheck，没有实现就是就是readiness healthChecker

2021-08-17 16:59 UTC, it-linnan commented on sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/HealthCheckerProcessor.java
> +                    .submitTask(environment, healthChecker::isHealthy);
这里最开始考虑了要不要做成并发检查，已修改为单线程线程池。

2021-08-17 17:00 UTC, it-linnan commented on sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/constant/SofaBootConstants.java
> +    public static final int     SOFABOOT_HEALTH_CHECK_DEFAULT_TIMEOUT_VALUE                  = 10 * 1000;
已修改为60s

2021-08-17 17:01 UTC, it-linnan commented on sofa-boot-project/sofa-boot/src/main/java/com/alipay/sofa/boot/constant/SofaBootConstants.java
> +     * thread pool core size to execute health check.
由于已经修改为单线程线程池，这个常量最终去掉了。

2021-08-18 06:14 UTC, HzjNeverStop commented on sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/core/HealthCheckExecutor.java
> +    public static Future<Health> submitTask(Environment environment, Callable<Health> callable) {
这里的environment没用到吧？

2021-08-18 06:14 UTC, HzjNeverStop commented on sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/core/HealthCheckExecutor.java
> +import com.alipay.sofa.boot.constant.SofaBootConstants;
unused import

2021-08-18 06:14 UTC, HzjNeverStop commented on sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/core/HealthCheckExecutor.java
> +        if (THREAD_POOL_REF.get() == null) {
这里不会有并发，不需要cas。

2021-08-18 06:14 UTC, HzjNeverStop commented on sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/core/HealthCheckExecutor.java
> +public class HealthCheckExecutor {
如果这个线程池只在HealthCheckerProcessor和HealthIndicatorProcessor中使用，直接在对应的bean中实例化即可

2021-08-18 06:14 UTC, HzjNeverStop commented on sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/HealthCheckerProcessor.java
>          boolean result = healthCheckers.entrySet().stream()
这里的两个stream操作应该可以合成一个

2021-08-21 10:49 UTC, it-linnan commented on sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/core/HealthCheckExecutor.java
> +    public static Future<Health> submitTask(Environment environment, Callable<Health> callable) {
已去掉

2021-08-21 10:49 UTC, it-linnan commented on sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/core/HealthCheckExecutor.java
> +import com.alipay.sofa.boot.constant.SofaBootConstants;
已去掉

2021-08-21 10:50 UTC, it-linnan commented on sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/HealthCheckerProcessor.java
>          boolean result = healthCheckers.entrySet().stream()
抱歉，我想了下，没有思路将两个操作合并成一个，您能给一些提示吗？

2021-08-21 11:21 UTC, it-linnan commented on sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/core/HealthCheckExecutor.java
> +        if (THREAD_POOL_REF.get() == null) {
去掉了AtomicReference

2021-08-21 11:24 UTC, it-linnan commented on sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/core/HealthCheckExecutor.java
> +public class HealthCheckExecutor {
实例化修改到THREAD_POOL_REF声明属性的地方，是否可以？

2021-08-23 01:09 UTC, it-linnan commented
@alaneuler @HzjNeverStop 两位早，提出的评审问题已做了相应的修改。

2021-08-24 12:23 UTC, HzjNeverStop commented on sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/core/HealthCheckExecutor.java
> +public class HealthCheckExecutor {
> 实例化修改到THREAD_POOL_REF声明属性的地方，是否可以？

可以的，检查完了就销毁掉

2021-08-24 12:23 UTC, HzjNeverStop commented on sofa-boot-project/sofa-boot-core/healthcheck-sofa-boot/src/main/java/com/alipay/sofa/healthcheck/HealthCheckerProcessor.java
>          boolean result = healthCheckers.entrySet().stream()
我描述不正确，是.filter(healthChecker -> !(healthChecker instanceof NonReadinessCheck))可以只做一次，后面的逻辑是不能合的

2021-08-30 05:28 UTC, alaneuler commented
@it-linnan CI 出错了，你看下错误，应该是没有 format

2021-08-30 06:03 UTC, it-linnan commented
> @it-linnan CI 出错了，你看下错误，应该是没有 format

代码格式化后提交了。

2021-08-31 07:07 UTC, alaneuler commented
最后的一些小优化 @it-linnan，麻烦 check 一下哈～

改动内容如下：
1. 去掉了 HealthCheckerProcessor 中多余的 environment 变量
2. stream 使用优化
3. 一些小的格式化，详见分支

2021-08-31 07:40 UTC, it-linnan commented
> 最后的一些小优化 @it-linnan，麻烦 check 一下哈～
> 
> 改动内容如下：
> 
> 1. 去掉了 HealthCheckerProcessor 中多余的 environment 变量
> 2. stream 使用优化
> 3. 一些小的格式化，详见 commit 内容
> 4. 合并最新 master 代码
> 
> 如果没有问题的话，我就合并掉了。

stream优化部分有些问题，在执行过collect方法后，流会关闭掉。继续执行map-reduce会抛出异常（java.lang.IllegalStateException: stream has already been operated upon or closed）

2021-08-31 07:50 UTC, alaneuler commented
> > 最后的一些小优化 @it-linnan，麻烦 check 一下哈～
> > 改动内容如下：
> > 
> > 1. 去掉了 HealthCheckerProcessor 中多余的 environment 变量
> > 2. stream 使用优化
> > 3. 一些小的格式化，详见 commit 内容
> > 4. 合并最新 master 代码
> > 
> > 如果没有问题的话，我就合并掉了。
> 
> stream优化部分有些问题，在执行过collect方法后，流会关闭掉。继续执行map-reduce会抛出异常（java.lang.IllegalStateException: stream has already been operated upon or closed）

嗯嗯，其他还有嘛

2021-08-31 07:58 UTC, it-linnan commented
> > > 最后的一些小优化 @it-linnan，麻烦 check 一下哈～
> > > 改动内容如下：
> > > 
> > > 1. 去掉了 HealthCheckerProcessor 中多余的 environment 变量
> > > 2. stream 使用优化
> > > 3. 一些小的格式化，详见 commit 内容
> > > 4. 合并最新 master 代码
> > > 
> > > 如果没有问题的话，我就合并掉了。
> > 
> > 
> > stream优化部分有些问题，在执行过collect方法后，流会关闭掉。继续执行map-reduce会抛出异常（java.lang.IllegalStateException: stream has already been operated upon or closed）
> 
> 嗯嗯，其他还有嘛

没有问题了!

2021-08-31 08:11 UTC, alaneuler approved these changes

2021-08-31 08:11 UTC, merged