add provider register mock
sofastack/sofa-boot pull request #858
Opened 2021-08-20 07:16 UTC by EvenLjj

add provider register mock

2021-08-21 11:27 UTC, OrezzerO requested changes

2021-08-21 11:27 UTC, OrezzerO commented on sofa-boot-project/sofa-boot-autoconfigure/src/main/java/com/alipay/sofa/boot/autoconfigure/rpc/SofaRpcAutoConfiguration.java
> +import com.alipay.sofa.rpc.boot.runtime.adapter.processor.*;
do not use * at import statement

2021-08-21 11:27 UTC, OrezzerO commented on sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/config/SofaBootRpcConfigKeys.java
> +                                                                 new String[] { "disable_confreg_pub" });
should be `disable_confireg_pub`

2021-08-21 11:27 UTC, OrezzerO commented on sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/test/java/com/alipay/sofa/rpc/boot/test/runtime/adapter/processor/ProviderRegisterProcessorTest.java
> +        Assert.assertFalse(providerConfig.isRegister());
System properties should roll back

2021-08-21 11:27 UTC, OrezzerO commented on sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/runtime/adapter/processor/ProviderRegisterProcessor.java
> +public class ProviderRegisterProcessor implements ProviderConfigProcessor {
class name can not indicate the function of this class

2021-08-30 03:50 UTC, OrezzerO approved these changes
LGTM

2021-08-31 08:48 UTC, alaneuler commented
fix: https://github.com/sofastack/sofa-boot/issues/859

2021-08-31 08:52 UTC, merged