Add errorcode
sofastack/sofa-boot pull request #867
Opened 2021-08-31 02:25 UTC by HzjNeverStop

2021-09-01 04:58 UTC, alaneuler requested changes

2021-09-01 04:58 UTC, alaneuler commented on sofa-boot-project/sofa-boot/src/main/resources/sofa-boot/log-codes.properties
> +
这么多空行是干嘛

2021-09-01 04:58 UTC, alaneuler commented on sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/SofaServiceAndReferenceTest.java
> +                                + "sofa-default.log");
这个文件名为啥变了

2021-09-01 04:58 UTC, alaneuler commented on sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/client/ServiceClientImpl.java
> +                throw new ServiceRuntimeException(String.format(ErrorCode.convert("01-00200"),
感觉这里可以在 sofa-common-tools 里面加上一个方法，convert 里面，能够接受额外参数，然后使用 String.format 来格式化。

String.format 到处都在使用。

2021-09-01 05:57 UTC, HzjNeverStop commented on sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/test/java/com/alipay/sofa/runtime/test/SofaServiceAndReferenceTest.java
> +                                + "sofa-default.log");
SofaService was already registered 改成warn级别日志了

2021-09-01 05:57 UTC, HzjNeverStop commented on sofa-boot-project/sofa-boot/src/main/resources/sofa-boot/log-codes.properties
> +
方便看。。

2021-09-01 05:57 UTC, HzjNeverStop commented on sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/service/client/ServiceClientImpl.java
> +                throw new ServiceRuntimeException(String.format(ErrorCode.convert("01-00200"),
嗯是可以

2021-09-02 01:56 UTC, alaneuler approved these changes
LGTM

2021-09-02 01:56 UTC, merged